export const motivationalMessages = [
  "Each day is a chance to rewrite your path.",
  "The clock’s running, chase what sets your soul on fire.",
  "Don’t let the months slip through your fingers.",
  "Your life’s too short for ‘someday’, start now.",
  "Every sunrise is an invitation to grow.",
  "The year’s progress is yours to shape.",
  "Stop waiting. This moment is where it begins.",
  "Make the days matter more than the percentage.",
  "Time’s moving fast, don’t leave dreams behind.",
  "You’re not just passing time, you’re building a legacy.",
  "The bar's filling up, make every inch count.",
  "Don’t count the days; make them unforgettable.",
  "Progress isn’t just time, it’s what you do with it.",
  "This year’s yours to conquer, one choice at a time.",
  "The months don’t pause, keep up with your heart.",
  "Every moment’s a spark, light up your purpose.",
  "You've got time left, but not forever. Act now.",
  "The year’s bar is rising, rise with it.",
  "Don’t let the calendar outpace your courage.",
  "Life’s too big to fit in a grid, break the mold.",
  "When are you going to act?",
  "Clock’s ticking. You ready?",
  "Dreams don’t sleep. Wake up.",
  "Take you best shot.",
  "Try your best, go beyond.",
  "Time's moving quicker than you think.",
  "Excuses don't affect the outcome.",
  "Are you really trying?",
  "Is this all you’ve got?",
  "Time's passing. Where's your mark?",
  "Are you living or just waiting?",
  "What’s your next move?",
  "Days pile up. What’s yours?",
  "Is this the story you’d tell?",
  "The clock doesn't care. Do you?",
  "What will you leave behind?",
  "Time is now.",
  "Are you going to sit down and relax or act?",
  "The future's built in the present. What are you building?",
  "Another day passed. Did you move forward?",
  "Your potential doesn’t wait for perfect timing.",
  "The year won’t slow down for your excuses.",
  "What’s stopping you? Really, what is it?",
  "You have 365 chances. How many will you take?",
  "The calendar's turning. Are you?",
  "Stop planning. Start doing.",
  "Your comfort zone is shrinking. Expand it.",
  "The days are numbered. Make them count.",
  "Tomorrow’s not promised. Today is.",
];
